---
- hosts: nexus
  pre_tasks:
    - name: Update all the packages
      yum:
        name: '*'
        state: latest
      become: true

- name: Install Dependencies
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
        - libselinux-python #used for final SELinux Edit
  become: true

  roles:
    - { role: java }
    - { role: nexus }
    - { role: httpd }
