---
- name: Create Nexus Service User
  user:
    name: nexus
    comment: "Service Account for the Nexus System"
  become: true

- name: Create nexus Directory
  file:
    path: '{{ item }}'
    state: directory
    owner: nexus
    mode: 0777
  with_items:
    - /etc/nexus

- name: download and unzip nexus files
  unarchive:
    src: http://download.sonatype.com/nexus/3/nexus-3.6.0-02-unix.tar.gz
    dest: /etc/nexus
    owner: nexus
    mode: 0777
    remote_src: yes
  become: true

- name: copy service
  copy:
    src: nexus.service
    dest: /etc/systemd/system/nexus.service
  become: true

- name: Start and Enable nexus Service
  systemd:
    name: nexus
    state: started
    enabled: yes
    daemon_reload: yes
  become: true
